spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration-time: ${JWT_EXPIRATION_TIME}
      refresh-secret-key: ${JWT_REFRESH_SECRET_KEY}
      refresh-expiration-time: ${JWT_REFRESH_EXPIRATION_TIME}
  kafka:
    bootstrap-address: ${KAFKA_BOOTSTRAP_ADDRESS}


server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health, info